package io.github.openpaydev.mpesa.backend.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.github.openpaydev.mpesa.backend.utils.MpesaCallbackParser;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * Represents the entire JSON object received from M-Pesa on the callback URL after a transaction.
 * <p>
 * This is the root object of the callback payload.
 * Use {@link MpesaCallbackParser} to parse the raw JSON into this object.
 */
@Getter
@Setter
@ToString
public class StkCallback {

    @JsonProperty("Body")
    private Body body;

    /**
     * The main container for the callback data.
     */
    @Getter
    @Setter
    @ToString
    public static class Body {

        @JsonProperty("stkCallback")
        private StkCallbackData stkCallback;
    }

    /**
     * Contains the core details and result of the STK Push transaction.
     */
    @Getter
    @Setter
    @ToString
    public static class StkCallbackData {

        /**
         * The unique identifier for the transaction that was sent by the merchant.
         */
        @JsonProperty("MerchantRequestID")
        private String merchantRequestID;

        /**
         * The unique identifier for the transaction that was generated by the M-Pesa system.
         */
        @JsonProperty("CheckoutRequestID")
        private String checkoutRequestID;

        /**
         * The numeric status code of the transaction. A value of 0 indicates success.
         * Any other value indicates a failure or cancellation.
         */
        @JsonProperty("ResultCode")
        private int resultCode;

        /**
         * A description of the result code.
         * Example: "The service request is processed successfully."
         */
        @JsonProperty("ResultDesc")
        private String resultDesc;

        /**
         * An object containing metadata about the transaction, such as the amount and phone number.
         * This field is only present if the transaction was successful (ResultCode = 0).
         */
        @JsonProperty("CallbackMetadata")
        private CallbackMetadata callbackMetadata;
    }

    /**
     * A container for the list of metadata items.
     */
    @Getter
    @Setter
    @ToString
    public static class CallbackMetadata {

        @JsonProperty("Item")
        private CallbackItem[] items;
    }

    /**
     * A key-value pair representing a piece of transaction metadata.
     */
    @Getter
    @Setter
    @ToString
    public static class CallbackItem {

        /**
         * The name of the metadata item.
         * Examples: "Amount", "MpesaReceiptNumber", "TransactionDate", "PhoneNumber".
         */
        @JsonProperty("Name")
        private String name;

        /**
         * The value associated with the metadata item.
         * Can be a number (e.g., 10.0 for Amount) or a string (e.g., "RABC123XYZ" for MpesaReceiptNumber).
         */
        @JsonProperty("Value")
        private Object value;
    }
}