package io.github.openpaydev.mpesa.backend.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * Represents the synchronous response received from the M-Pesa API immediately after initiating an STK Push.
 * <p>
 * This is NOT the final result of the transaction. This object confirms that M-Pesa has received
 * the request and is processing it. The final result will be sent to your callback URL.
 */
@Getter
@Setter
@ToString
@NoArgsConstructor
public class StkPushResponse {

    /**
     * A unique identifier for the transaction that was provided by the merchant's system.
     */
    @JsonProperty("MerchantRequestID")
    private String merchantRequestID;

    /**
     * A unique identifier for the transaction generated by the M-Pesa system.
     * <p>
     * <b>Important:</b> This is the ID you must use to query the status of the transaction later.
     */
    @JsonProperty("CheckoutRequestID")
    private String checkoutRequestID;

    /**
     * The status code of the request. A value of "0" indicates that the request was successfully received
     * and is being processed. Any other value indicates an error with the initial request.
     */
    @JsonProperty("ResponseCode")
    private String responseCode;

    /**
     * A brief description of the response code.
     * Example: "Success. Request accepted for processing"
     */
    @JsonProperty("ResponseDescription")
    private String responseDescription;

    /**
     * A message that can be displayed to the end-user.
     * Example: "Success. Request accepted for processing"
     */
    @JsonProperty("CustomerMessage")
    private String customerMessage;
}