package io.github.openpaydev.mpesa.backend.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.github.openpaydev.mpesa.backend.MpesaClient;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * Represents the internal request payload for the M-Pesa STK Push Status Query API.
 * <p>
 * This class is an internal model and is not intended to be used directly by the SDK consumer.
 * The {@link MpesaClient} creates and populates this object.
 */
@Getter
@Setter
@AllArgsConstructor
@ToString
public class StkStatusQueryRequest {

    /**
     * The organization's short code (Paybill or Till Number) used to identify the business.
     */
    @JsonProperty("BusinessShortCode")
    private String businessShortCode;

    /**
     * The Base64 encoded password, generated from the business short code, passkey, and timestamp.
     */
    @JsonProperty("Password")
    private String password;

    /**
     * The timestamp of the request in the format yyyyMMddHHmmss.
     */
    @JsonProperty("Timestamp")
    private String timestamp;

    /**
     * The unique ID generated by the M-Pesa system for the original STK Push request, which is to be queried.
     */
    @JsonProperty("CheckoutRequestID")
    private String checkoutRequestID;
}