package io.github.openpaydev.mpesa.core.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Builder;
import lombok.Value;
import lombok.extern.jackson.Jacksonized;

/**
 * Represents the response object received when querying the status of an STK Push transaction.
 * <p>
 * This object contains the results of a transaction status query, indicating whether the
 * transaction was successful, is still pending, or has failed.
 */
@Value
@Jacksonized
@Builder
@JsonIgnoreProperties(ignoreUnknown = true)
public class StkStatusQueryResponse {

    /**
     * The status code of the initial query request itself.
     * A value of "0" indicates that the query request was accepted for processing.
     */
    @JsonProperty("ResponseCode")
    String responseCode;

    /**
     * A brief description of the status of the query request.
     * Example: "Accepted for processing"
     */
    @JsonProperty("ResponseDescription")
    String responseDescription;

    /**
     * The unique identifier for the transaction that was sent by the merchant.
     * This is the same ID that was used in the initial STK Push request.
     */
    @JsonProperty("MerchantRequestID")
    String merchantRequestID;

    /**

     * The unique identifier for the transaction that was generated by the M-Pesa system.
     */
    @JsonProperty("CheckoutRequestID")
    String checkoutRequestID;

    /**
     * The status code indicating the final result of the transaction.
     * "0" means the transaction was successful.
     * Any other value indicates a failure or a pending state.
     */
    @JsonProperty("ResultCode")
    String resultCode;

    /**
     * A detailed description of the transaction's final result.
     * Example: "The service request is processed successfully."
     */
    @JsonProperty("ResultDesc")
    String resultDesc;
}