package io.github.openpaydev.mpesa.core.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Builder;
import lombok.Value;
import lombok.extern.jackson.Jacksonized;
/**
 * Represents the internal request payload for the M-Pesa STK Push Status Query API.
 * <p>
 * This class is an internal model and is not intended to be used directly by the SDK consumer.
 * The {@code MpesaClient} creates and populates this object.
 */
@Value
@Jacksonized
@Builder
@JsonIgnoreProperties(ignoreUnknown = true)
public class StkStatusQueryRequest {

    /**
     * The organization's short code (Paybill or Till Number) used to identify the business.
     */
    @JsonProperty("BusinessShortCode")
    String businessShortCode;

    /**
     * The Base64 encoded password, generated from the business short code, passkey, and timestamp.
     */
    @JsonProperty("Password")
    String password;

    /**
     * The timestamp of the request in the format yyyyMMddHHmmss.
     */
    @JsonProperty("Timestamp")
    String timestamp;

    /**
     * The unique ID generated by the M-Pesa system for the original STK Push request, which is to be queried.
     */
    @JsonProperty("CheckoutRequestID")
    String checkoutRequestID;
}